"""
Test to verify Python TiltSeries angle calculations match C# reference implementation.

This test uses reference data generated by the C# version of TiltSeries for the central
position in a volume, comparing the calculated tilt angles against the reference values.
"""

import pytest
import torch
import starfile
from pathlib import Path

from warpylib.tilt_series import TiltSeries


class TestTiltSeriesCSharpComparison:
    """Test that Python TiltSeries produces identical results to C# implementation"""

    def test_angles_match_csharp_reference(self):
        """
        Test that angles calculated for all reference points match C# reference values.

        The C# version wrote out all 2D positions and angles for multiple 3D positions
        in the volume. We load this reference data and compare our Python implementation.
        """
        # Define test data paths
        test_dir = Path(__file__).parent.parent / "testdata"
        xml_path = test_dir / "TS_1.xml"
        star_path = test_dir / "TS_1.star"

        # Load the TiltSeries from XML
        ts = TiltSeries(
            path=str(xml_path),
            volume_dimensions_physical=torch.tensor([1000.0, 1000.0, 1000.0]),
            image_dimensions_physical=torch.tensor([1000.0, 1000.0])
        )

        # Load the reference data from the STAR file
        star_data = starfile.read(star_path)

        # Get the reference 3D coordinates from data_points block
        # These are in centered coordinates, need to convert to absolute
        points = star_data['points']
        n_points = len(points)
        volume_center = ts.volume_dimensions_physical / 2

        # Convert centered coordinates to absolute coordinates
        reference_coords = torch.zeros((n_points, 3), dtype=torch.float32)
        for i in range(n_points):
            reference_coords[i, 0] = points.iloc[i]['centeredCoordinateXAngst'] + volume_center[0]
            reference_coords[i, 1] = points.iloc[i]['centeredCoordinateYAngst'] + volume_center[1]
            reference_coords[i, 2] = points.iloc[i]['centeredCoordinateZAngst'] + volume_center[2]

        # Get the reference angles from the mappings block
        mappings = star_data['mappings']
        n_mappings = len(mappings)

        assert n_mappings == n_points * ts.n_tilts, \
            f"Expected {n_points * ts.n_tilts} mappings, got {n_mappings}"

        # Process each point
        total_comparisons = 0
        from warpylib.euler import euler_to_matrix

        # Print header for first point
        print("\n" + "="*80)
        print("ANGLE COMPARISON - First Point (all in degrees)")
        print("="*80)

        for point_idx in range(n_points):
            point_id = point_idx + 1  # Point IDs are 1-indexed
            reference_coord = reference_coords[point_idx]

            # Get mappings for this point
            point_mappings = mappings[mappings['pointID'] == point_id]
            assert len(point_mappings) == ts.n_tilts, \
                f"Point {point_id}: expected {ts.n_tilts} mappings, got {len(point_mappings)}"

            # Extract reference angles (in degrees from STAR file)
            reference_angles_deg = torch.zeros((ts.n_tilts, 3), dtype=torch.float32)
            for i, (_, row) in enumerate(point_mappings.iterrows()):
                reference_angles_deg[i, 0] = row['angleRot']
                reference_angles_deg[i, 1] = row['angleTilt']
                reference_angles_deg[i, 2] = row['anglePsi']

            # Convert reference angles to radians
            reference_angles_rad = reference_angles_deg * (torch.pi / 180.0)

            # Calculate angles using our Python implementation
            calculated_angles = ts.get_angle_in_all_tilts_single(reference_coord)

            # Print comparison for first point
            if point_idx == 0:
                calculated_angles_deg = calculated_angles * (180.0 / torch.pi)
                centered_coord = reference_coord - volume_center
                print(f"Point {point_id} at centered coords {centered_coord.tolist()}")
                print(f"{'Tilt':<6} {'Ref Rot':>12} {'Calc Rot':>12} {'Ref Tilt':>12} {'Calc Tilt':>12} {'Ref Psi':>12} {'Calc Psi':>12}")
                print("-"*80)
                for i in range(min(ts.n_tilts, 10)):
                    print(f"{i:<6} "
                          f"{reference_angles_deg[i, 0]:>12.4f} {calculated_angles_deg[i, 0]:>12.4f} "
                          f"{reference_angles_deg[i, 1]:>12.4f} {calculated_angles_deg[i, 1]:>12.4f} "
                          f"{reference_angles_deg[i, 2]:>12.4f} {calculated_angles_deg[i, 2]:>12.4f}")
                if ts.n_tilts > 10:
                    print(f"... ({ts.n_tilts - 10} more tilts)")
                print("="*80 + "\n")

            # Compare angles via rotation matrices
            for i in range(ts.n_tilts):
                # Convert both to rotation matrices
                ref_matrix = euler_to_matrix(
                    reference_angles_rad[i, 0].unsqueeze(0),
                    reference_angles_rad[i, 1].unsqueeze(0),
                    reference_angles_rad[i, 2].unsqueeze(0)
                ).squeeze(0)

                calc_matrix = euler_to_matrix(
                    calculated_angles[i, 0].unsqueeze(0),
                    calculated_angles[i, 1].unsqueeze(0),
                    calculated_angles[i, 2].unsqueeze(0)
                ).squeeze(0)

                # Matrices should be very close
                if not torch.allclose(ref_matrix, calc_matrix, atol=1e-4, rtol=1e-4):
                    calculated_angles_deg = calculated_angles * (180.0 / torch.pi)
                    print(f"\nPoint {point_id}, Tilt {i}:")
                    print(f"  Coordinate: {reference_coord}")
                    print(f"  Reference angles (deg): {reference_angles_deg[i]}")
                    print(f"  Calculated angles (deg): {calculated_angles_deg[i]}")
                    print(f"  Reference matrix:\n{ref_matrix}")
                    print(f"  Calculated matrix:\n{calc_matrix}")
                    print(f"  Matrix difference:\n{ref_matrix - calc_matrix}")

                assert torch.allclose(ref_matrix, calc_matrix, atol=1e-4, rtol=1e-4), \
                    f"Rotation matrices don't match for point {point_id}, tilt {i}"

                total_comparisons += 1

        print(f"\nSuccessfully validated {total_comparisons} angle calculations ({n_points} points × {ts.n_tilts} tilts) against C# reference implementation!")

    def test_positions_match_csharp_reference(self):
        """
        Test that 2D positions/shifts calculated for all reference points match C# reference values.

        The C# version wrote out centered coordinates (with image center subtracted) for multiple
        3D positions. We need to convert our absolute positions to centered coordinates for comparison.
        """
        # Define test data paths
        test_dir = Path(__file__).parent.parent / "testdata"
        xml_path = test_dir / "TS_1.xml"
        star_path = test_dir / "TS_1.star"

        # Image dimensions as defined in test (1000x1000 Angstroms)
        image_dimensions = torch.tensor([1000.0, 1000.0])
        image_center = image_dimensions / 2  # [500, 500]

        # Load the TiltSeries from XML
        ts = TiltSeries(
            path=str(xml_path),
            volume_dimensions_physical=torch.tensor([1000.0, 1000.0, 1000.0]),
            image_dimensions_physical=image_dimensions
        )

        # Load the reference data from the STAR file
        star_data = starfile.read(star_path)

        # Get the reference 3D coordinates from data_points block
        # These are in centered coordinates, need to convert to absolute
        points = star_data['points']
        n_points = len(points)
        volume_center = ts.volume_dimensions_physical / 2

        # Convert centered coordinates to absolute coordinates
        reference_coords = torch.zeros((n_points, 3), dtype=torch.float32)
        for i in range(n_points):
            reference_coords[i, 0] = points.iloc[i]['centeredCoordinateXAngst'] + volume_center[0]
            reference_coords[i, 1] = points.iloc[i]['centeredCoordinateYAngst'] + volume_center[1]
            reference_coords[i, 2] = points.iloc[i]['centeredCoordinateZAngst'] + volume_center[2]

        # Get the reference positions from the mappings block
        mappings = star_data['mappings']
        n_mappings = len(mappings)

        assert n_mappings == n_points * ts.n_tilts, \
            f"Expected {n_points * ts.n_tilts} mappings, got {n_mappings}"

        # Process each point
        total_comparisons = 0

        # Print header for first point
        print("\n" + "="*80)
        print("POSITION COMPARISON - First Point (centered coordinates in Angstroms)")
        print("="*80)

        for point_idx in range(n_points):
            point_id = point_idx + 1  # Point IDs are 1-indexed
            reference_coord = reference_coords[point_idx]

            # Get mappings for this point
            point_mappings = mappings[mappings['pointID'] == point_id]
            assert len(point_mappings) == ts.n_tilts, \
                f"Point {point_id}: expected {ts.n_tilts} mappings, got {len(point_mappings)}"

            # Extract reference centered coordinates (in Angstroms from STAR file)
            reference_centered_coords = torch.zeros((ts.n_tilts, 2), dtype=torch.float32)
            for i, (_, row) in enumerate(point_mappings.iterrows()):
                reference_centered_coords[i, 0] = row['centeredCoordinateXAngst']
                reference_centered_coords[i, 1] = row['centeredCoordinateYAngst']

            # Calculate positions using our Python implementation
            calculated_positions = ts.get_position_in_all_tilts_single(reference_coord)

            # Convert absolute positions to centered coordinates by subtracting image center
            calculated_centered_coords = calculated_positions[:, :2] - image_center

            # All results should be finite
            assert torch.all(torch.isfinite(calculated_centered_coords)), \
                f"Point {point_id}: Some calculated positions are not finite"

            # Print comparison for first point
            if point_idx == 0:
                centered_coord = reference_coord - volume_center
                print(f"Point {point_id} at centered coords {centered_coord.tolist()}")
                print(f"{'Tilt':<6} {'Ref X':>12} {'Calc X':>12} {'Diff X':>12} {'Ref Y':>12} {'Calc Y':>12} {'Diff Y':>12}")
                print("-"*80)
                for i in range(min(ts.n_tilts, 10)):
                    diff_x = calculated_centered_coords[i, 0] - reference_centered_coords[i, 0]
                    diff_y = calculated_centered_coords[i, 1] - reference_centered_coords[i, 1]
                    print(f"{i:<6} "
                          f"{reference_centered_coords[i, 0]:>12.4f} {calculated_centered_coords[i, 0]:>12.4f} {diff_x:>12.4f} "
                          f"{reference_centered_coords[i, 1]:>12.4f} {calculated_centered_coords[i, 1]:>12.4f} {diff_y:>12.4f}")
                if ts.n_tilts > 10:
                    print(f"... ({ts.n_tilts - 10} more tilts)")
                print("="*80 + "\n")

            # Compare positions with reasonable tolerance
            for i in range(ts.n_tilts):
                if not torch.allclose(
                    calculated_centered_coords[i],
                    reference_centered_coords[i],
                    atol=0.01,  # 0.01 Angstrom tolerance
                    rtol=1e-4
                ):
                    print(f"\nPoint {point_id}, Tilt {i}:")
                    print(f"  Coordinate: {reference_coord}")
                    print(f"  Reference position: {reference_centered_coords[i]}")
                    print(f"  Calculated position: {calculated_centered_coords[i]}")
                    print(f"  Difference: {calculated_centered_coords[i] - reference_centered_coords[i]}")

                assert torch.allclose(
                    calculated_centered_coords[i],
                    reference_centered_coords[i],
                    atol=0.01,
                    rtol=1e-4
                ), f"Position mismatch for point {point_id}, tilt {i}"

                total_comparisons += 1

        print(f"\nSuccessfully validated {total_comparisons} position calculations ({n_points} points × {ts.n_tilts} tilts) against C# reference implementation!")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
